# Generated by Django 5.2.1 on 2025-05-21 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='faculty_name', max_length=255)),
            ],
            options={
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='group_name', max_length=255)),
                ('faculty', models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='FacultyListApp.faculty')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(db_column='birth_date')),
                ('phone', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0)),
                ('group', models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FacultyListApp.group')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
